#**Numpy**

In [ ]:
import numpy as np

#**View vs copy**
*  Copy is a new array, and the View is just a view of the orignal array.
*  Any changes made to a copy will not affect orignal array.
*  Any changes to the view will affect the orignal array.

In [ ]:
arr = np.array([1,2,3,4,5])
# copy method
copy = arr.copy()
copy[0] = 42
print(arr)
print(copy)

[1 2 3 4 5]
[42  2  3  4  5]


In [ ]:
#view method
view = arr.view()
view[0] = 42
print (arr)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]


#**Append, Insert and Delete operations**

In [ ]:
#append operation
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
print("2D Array-->",a)
np.append(a, [7,8,9])    #axis = 0 i.e row and axis = 1 i.e column



(2, 3)
2D Array--> [[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Default it will add one more row to it.
np.append(a, [[7,8,9]],axis=0) # for Row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.append(a,[[5],[8]],axis=1)  # for column

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [ ]:
# insert operation
a = np.array([[1,2],
              [3,4],                                      # 0 1 2
              [5,6]])                                     # ^ ^ ^
# insert method                                           # | | |
np.insert(a,3,[11,12])   #default in row at which position (1,2,3) 3rd position
        # (which array, position , elements added)

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [ ]:
np.insert(a,1,[11,12],axis=0)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [ ]:
np.insert(a,1,[11,12,13],axis=1)

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 13,  6]])

In [ ]:
#Delete operation
a = np.array([[1,2,3,12],
              [9,5,6,11],
              [8,4,10,7]])
#Delete Method
np.delete(a,4)

array([ 1,  2,  3, 12,  5,  6, 11,  8,  4, 10,  7])

In [ ]:
np.delete(a,1,axis=1)

array([[ 1,  3, 12],
       [ 9,  6, 11],
       [ 8, 10,  7]])

In [ ]:
np.delete(a,1,axis=0)

array([[ 1,  2,  3, 12],
       [ 8,  4, 10,  7]])

#**Numpy Dimentional arrays**
*  One Dimentional
*  Two Dimentional
*  3D Array

In [ ]:
import numpy as np
one = np.array([1,2,3,4,5])
two = np.array([[1,2,3],
     [4,5,6]])
three = np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]]])
print(np.ndim(one))
print(np.ndim(two))
print(np.ndim(three))

1
2
3


In [ ]:
three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
three.shape

(2, 2, 3)

#**Numpy Arrays VS Lists**
*  In array we only have single datatype.(Disadvantage)
*  In list we cannot perform mathematical operations in one line

In [ ]:
list1=[1,2,3.15,"Apple"]
list1

[1, 2, 3.15, 'Apple']

In [ ]:
arr1=np.array([1,2,3.14,"apple"])    #type conversion
arr1

array(['1', '2', '3.14', 'apple'], dtype='<U32')

In [ ]:
l=[1,2,3,4]
l/5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
arr=np.array([1,2,3.15])
arr/5

array([0.2 , 0.4 , 0.63])

#**More advantages of lists over array**
*  Arrays are much faster than Lists.
*  Array consumes less memory.

#**Slicing of arrays**
*  slicing in python means taking elements from the given index to another given index.
*  we pass slice instead of index like this. [start:end]
*  we can also decide the step,like this. [start:endstep]

In [ ]:
import numpy as np
a1 =np.array([1,2,3,4,5,6,7])
print(a1[1:5])  #slicing       Starting point included  but ending point is not included

[2 3 4 5]


In [ ]:
print(a1[1])  #indexing

2


In [ ]:
a1[:4]

array([1, 2, 3, 4])

In [ ]:
a2 =np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
a2[1, 1:4]    #Syntax -> [row,column(start:end)]

array([7, 8, 9])

In [ ]:
a2[0:2, 2]

array([3, 8])

In [ ]:
print(a2)
a2[1: , :5]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 6,  7,  8,  9, 10]])

In [ ]:
#3D Arrays



#**Reshaping array**
*  tip-> try that the oldshape(row*col)== newshape(row*col)

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])  #1D array

#1D to 2D
newarr = arr.reshape(2,6)   #2*6=12

In [ ]:
print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
#1D to 3D
new_arr = arr.reshape(2,3,2)   #2*3*2=12

In [ ]:
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
print(np.ndim(new_arr))

3


#**Numpy Array Indexing**
*  Array indexing is the same as accessing an array element
*  You can access an array element by referring to it's index number

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[3])

4


In [ ]:
#mathematical operations
print(arr[1] + arr[2])

5


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr.shape

(2, 5)

In [ ]:
print(arr[1,3])

9


In [ ]:
print(arr[0,4])

5


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr.shape

(2, 2, 3)

In [ ]:
print(arr[1,0,2])

9


#**Numpy Additional Topics**
#**Hstack vs Vstack**
*  **Hstack is used to**join two arrays **Horizontally**
*  **Vstack is used to**join two arrays **vertically**


In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
print(a,b)
print(np.ndim(a),np.ndim(b))

[1 2 3] [4 5 6]
1 1


In [ ]:
#performing Hstack

result=np.hstack((a,b))
print(result)
print(np.ndim(result))

[1 2 3 4 5 6]
1


In [ ]:
#performing Vstack

result=np.vstack((a,b))
print(result)
print(np.ndim(result))

[[1 2 3]
 [4 5 6]]
2


#**Numpy concatenation**
*  It is used to join the two or more arrays of the same shape along a specified axis
*  Axis=0, Adding a new row
*  Axis=1, Adding a new column

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[5,6,9],[7,8,10]])   #dimentions and the shape should be same

arr3 = np.array([[3],[9]])
arr4 = np.array([[10],[25]])

new = np.concatenate((arr1,arr2), axis=0)
print(new)
new = np.concatenate((arr3,arr4), axis=1)
print(new)



[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  9]
 [ 7  8 10]]
[[ 3 10]
 [ 9 25]]
